apiVersion: v1
kind: Service
metadata:
  name: springappsvc
spec:
  selector:
    app: springapp
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
