
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
  namespace: prod
  labels:
    type: deployment
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: springapp
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: mylandmarktech/spring-boot-mongo
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 250Mi
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
        - name: MONGO_DB_USERNAME
          value: ejimz
        - name: MONGO_DB_PASSWORD
          value: ejim1234
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
  namespace: prod
  labels:
    type: deployment
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: springapp
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: mylandmarktech/spring-boot-mongo
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 250Mi
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
        - name: MONGO_DB_USERNAME
          value: ejimz
        - name: MONGO_DB_PASSWORD
          value: ejimz1234
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
spec:
  selector:
    app: springapp
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springappdeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
