apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
  namespace: prod
  labels:
    type: deployment
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: springapp
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: mylandmarktech/spring-boot-mongo
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 250Mi
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
        - name: MONGO_DB_USERNAME
          value: ejimz
        - name: MONGO_DB_PASSWORD
          value: ejimz1234
        ports:
        - containerPort: 8080


